#!/bin/sh

set -e

#DEBHELPER#

mv /usr/lib/s4a/Media/Sounds/Music_Loops /usr/lib/s4a/Media/Sounds/Music\ Loops
mv /usr/lib/s4a/Projects/Interactive_Art /usr/lib/s4a/Projects/Interactive\ Art
mv /usr/lib/s4a/Projects/Music_and_Dance /usr/lib/s4a/Projects/Music\ and\ Dance
mv /usr/lib/s4a/Projects/Sensors_and_Motors /usr/lib/s4a/Projects/Sensors\ and\ Motors
mv /usr/lib/s4a/Projects/Speak_Up /usr/lib/s4a/Projects/Speak\ Up


