#! /bin/sh
set -e

# Lightdm-kde-greeter
change_lightdm_kde_theme() {
    if [ -d /etc/lightdm ]; then
		if [ -f /etc/lightdm/lightdm-kde-greeter.conf ]; then
			mv /etc/lightdm/lightdm-kde-greeter.conf /etc/lightdm/lightdm-kde-greeter.conf.ezgo-bak
		fi
		cp -f /usr/share/kde4/apps/lightdm-kde-greeter/themes/ezgo/lightdm-kde-greeter.conf /etc/lightdm/lightdm-kde-greeter.conf.ezgo
		ln -s /etc/lightdm/lightdm-kde-greeter.conf.ezgo /etc/lightdm/lightdm-kde-greeter.conf
	fi
}

restore_lightdm_kde_theme() {
    if [ -d /etc/lightdm ]; then
		if [ -f /etc/lightdm/lightdm-kde-greeter.conf.ezgo-bak ]; then
			rm -f /etc/lightdm/lightdm-kde-greeter.conf
			mv /etc/lightdm/lightdm-kde-greeter.conf.ezgo-bak /etc/lightdm/lightdm-kde-greeter.conf
		fi
	fi
}

## ksplash
change_ksplash() {
    update-alternatives --install \
	/usr/share/images/desktop-base/desktop-splash \
	desktop-splash \
	/usr/share/kde4/apps/kdm/themes/ezgo/background.png 65
}

restore_ksplash() {
    update-alternatives --remove desktop-splash \
	/usr/share/kde4/apps/kdm/themes/ezgo/background.png
}

change_ezgo_font_config() {
    if [ -f /usr/local/share/fonts/s/SourceHanSans-Normal.otf ]; then
	    sed -i 's/^\(font=\)[^,]\+/\1Source Han Sans/g' /usr/share/ezgo/ezgo-kde/kde-profile/share/config/kdeglobals /etc/skel/.kde/share/config/kdeglobals
	    sed -i 's/^\(menuFont=\)[^,]\+/\1Source Han Sans/g' /usr/share/ezgo/ezgo-kde/kde-profile/share/config/kdeglobals /etc/skel/.kde/share/config/kdeglobals
	    sed -i 's/^\(desktopFont=\)[^,]\+/\1Source Han Sans/g' /usr/share/ezgo/ezgo-kde/kde-profile/share/config/kdeglobals /etc/skel/.kde/share/config/kdeglobals
	    sed -i 's/^\(toolBarFont=\)[^,]\+/\1Source Han Sans/g' /usr/share/ezgo/ezgo-kde/kde-profile/share/config/kdeglobals /etc/skel/.kde/share/config/kdeglobals
	    sed -i 's/^\(smallestReadableFont=\)[^,]\+/\1Source Han Sans/g' /usr/share/ezgo/ezgo-kde/kde-profile/share/config/kdeglobals /etc/skel/.kde/share/config/kdeglobals
	    sed -i 's/^\(taskbarFont=\)[^,]\+/\1Source Han Sans/g' /usr/share/ezgo/ezgo-kde/kde-profile/share/config/kdeglobals /etc/skel/.kde/share/config/kdeglobals
	    sed -i 's/^\(activeFont=\)[^,]\+/\1Source Han Sans/g' /usr/share/ezgo/ezgo-kde/kde-profile/share/config/kdeglobals /etc/skel/.kde/share/config/kdeglobals
    fi
}

case "$1" in
  configure)
    change_lightdm_kde_theme
    change_ksplash
    change_ezgo_font_config
    ;;
  remove)
    restore_lightdm_kde_theme
    restore_ksplash
    ;;
esac
