#! /bin/sh
set -e

#  change_ldm_background() {
#      update-alternatives --install /usr/share/ldm/themes/default \
#          ldm-theme /usr/share/ldm/themes/debian-edu 85
#  }
#  
#  restore_ldm_background() {
#      update-alternatives --remove ldm-theme /usr/share/ldm/themes/debian-edu
#  }
#  
#  
#  ## GRUB
change_grub_background() {
    priority=60 # value higher than 50 used for debian-edu-splash-grub.png in desktop-base
    update-alternatives --install \
        /usr/share/images/desktop-base/desktop-grub.png \
        desktop-grub \
        /usr/share/ezgo/grub/ezgo-splash-grub.png $priority

    if which update-grub2 > /dev/null ; then
        sync
        update-grub2 || true
    fi
}
 
restore_grub_background() {
    update-alternatives --remove desktop-grub \
	/usr/share/ezgo/grub/ezgo-splash-grub.png

    if which update-grub2 > /dev/null ; then
        update-grub2 || true
    fi
}


## Wallpaper
change_desktop_background() {
    update-alternatives --install \
        /usr/share/images/desktop-base/desktop-background \
	desktop-background \
	/usr/share/images/desktop-base/ezgo-wallpaper-1440x900.png 80
    update-alternatives --install \
        /usr/share/images/desktop-base/desktop-background.xml \
	desktop-background.xml \
	/usr/share/images/desktop-base/ezgo-wallpaper.xml 30

    for WALLPAPER in ezgo-wallpaper-1440x900.png \
		ezgo-wallpaper-1024x768.png ; do
	update-alternatives --install \
	        /usr/share/images/desktop-base/desktop-background \
		desktop-background \
		/usr/share/images/desktop-base/$WALLPAPER 60
    done
}

restore_desktop_background() {
    update-alternatives --remove \
	desktop-background \
	/usr/share/images/desktop-base/ezgo-wallpaper-1440x900.png
    update-alternatives --remove \
	desktop-background.xml \
	/usr/share/images/desktop-base/ezgo-wallpaper.xml

    for WALLPAPER in ezgo-wallpaper-1440x900.png \
		ezgo-wallpaper-1024x768.png ; do
	update-alternatives --remove desktop-background \
		/usr/share/images/desktop-base/$WALLPAPER
    done
}

## Wallpaper
change_ksplash() {
    update-alternatives --install \
	/usr/share/images/desktop-base/desktop-splash \
	desktop-splash \
	/usr/share/kde4/apps/kdm/themes/ezgo/background.png 65
}

restore_ksplash() {
    update-alternatives --remove desktop-splash \
	/usr/share/kde4/apps/kdm/themes/ezgo/background.png
}

#  compile_gschemas() {
#      glib-compile-schemas /usr/share/glib-2.0/schemas/
#  }

case "$1" in
  configure)
#      change_ldm_background
    change_grub_background
    change_desktop_background
    change_ksplash
#      compile_gschemas
    ;;
  remove)
#      restore_ldm_background
    restore_grub_background
    restore_desktop_background
    restore_ksplash
#      compile_gschemas
    ;;
esac
