#!/bin/sh -e

# link desktop files for ezgo
ln -sf /usr/share/ezgo/desktop-files/my_computer.desktop /usr/share/applications/my_computer.desktop
ln -sf /usr/share/ezgo/desktop-files/my_ezgo.desktop /usr/share/applications/my_ezgo.desktop
ln -sf /usr/share/ezgo/desktop-files/update_ezgo.desktop /usr/share/applications/update_ezgo.desktop
ln -sf /usr/share/ezgo/desktop-files/about_ezgo.desktop /usr/share/applications/about_ezgo.desktop


#DEBHELPER#

exit 0
