#!/bin/sh -e

# link desktop files for ezgo
ln -sf /usr/share/ezgo/desktop-files/my_computer.desktop /usr/share/applications/my_computer.desktop
ln -sf /usr/share/ezgo/desktop-files/my_ezgo.desktop /usr/share/applications/my_ezgo.desktop
ln -sf /usr/share/ezgo/desktop-files/gcompris-qt.desktop /usr/share/applications/gcompris-qt.desktop
ln -sf /usr/share/ezgo/desktop-files/update_ezgo.desktop /usr/share/applications/update_ezgo.desktop
ln -sf /usr/share/ezgo/desktop-files/about_ezgo.desktop /usr/share/applications/about_ezgo.desktop
ln -sf /usr/share/ezgo/desktop-files/BlueGriffon-program.desktop /usr/share/applications/BlueGriffon-program.desktop
#ln -sf /usr/share/ezgo/desktop-files/install_scratch2.desktop /usr/share/applications/install_scratch2.desktop
#ln -sf /usr/share/ezgo/desktop-files/sweethome3d.desktop /usr/share/applications/sweethome3d.desktop
ln -sf /usr/share/ezgo/desktop-files/xmind.desktop /usr/share/applications/xmind.desktop
ln -sf /usr/share/ezgo/desktop-files/moedict.desktop /usr/share/applications/moedict.desktop


#DEBHELPER#

exit 0
