#!/bin/sh

set -e

#DEBHELPER#

# put ksnapshot.mo
if [ ! -e /usr/share/locale/zh_TW/LC_MESSAGES/ksnapshot.mo.ezgo-bak ]; then
    if [ -e /usr/share/locale/zh_TW/LC_MESSAGES/ksnapshot.mo ]; then
        cp -f  /usr/share/locale/zh_TW/LC_MESSAGES/ksnapshot.mo /usr/share/locale/zh_TW/LC_MESSAGES/ksnapshot.mo.ezgo-bak
    fi
fi
rm -f /usr/share/locale/zh_TW/LC_MESSAGES/ksnapshot.mo
cp -f /usr/share/ezgo/ezgo-misc/translations/ksnapshot.mo /usr/share/locale/zh_TW/LC_MESSAGES/ksnapshot.mo

