#!/bin/sh

set -e

#DEBHELPER#

# put klavaro.mo
if [ ! -e /usr/share/locale/zh_TW/LC_MESSAGES/klavaro.mo.ezgo-bak ]; then
    if [ -e /usr/share/locale/zh_TW/LC_MESSAGES/klavaro.mo ]; then
        cp -f  /usr/share/locale/zh_TW/LC_MESSAGES/klavaro.mo /usr/share/locale/zh_TW/LC_MESSAGES/klavaro.mo.ezgo-bak
    fi
fi
rm -f /usr/share/locale/zh_TW/LC_MESSAGES/klavaro.mo
cp -f /usr/share/ezgo/ezgo-misc/translations/klavaro.mo /usr/share/locale/zh_TW/LC_MESSAGES/klavaro.mo

