#!/bin/sh

CHEM_VERSION=ezgo12
CHEM_URL=ftp://goodhorse.idv.tw/debian-ezgo/ezgo-chem/chemstru_${CHEM_VERSION}.tar.gz
MD5_URL=ftp://goodhorse.idv.tw/debian-ezgo/ezgo-chem/chem.md5
OUTPUT_FILE=/usr/share/ezgo/ezgo-prt/chemstru_${CHEM_VERSION}.tar.gz
MD5_FILE=/usr/share/ezgo/ezgo-prt/chem.md5

mkdir -p /usr/share/ezgo/ezgo-prt/

echo "Downloading chemical_structure_${PHET_VERSION}..."

exit_with_error()
{
	echo $1
	exit 1
}

wget --continue -O $OUTPUT_FILE $CHEM_URL || exit_with_error "Download chemical structures file failed: $?"
wget --continue -O $MD5_FILE $MD5_URL || exit_with_error "Download md5 file failed: $?"

cd /usr/share/ezgo/ezgo-prt
md5sum -c $MD5_FILE || exit_with_error "md5 checksum error!"

tar xfz $OUTPUT_FILE
rm -f chemical_structures
ln -s chemical_structures_${CHEM_VERSION} chemical_structures
rm -f $MD5_FILE
rm -f $OUTPUT_FILE

#DEBHELPER#

exit 0
