#!/bin/sh

set -e

#DEBHELPER#

case "$1" in
  configure)
    cp -f /usr/share/ezgo/ezgo-kde5/defaultPanel.layout.js /usr/share/plasma/layout-templates/org.kde.plasma.desktop.defaultPanel/contents/layout.js
    cp -f /usr/share/ezgo/ezgo-kde5/desktop.layout.js /usr/share/plasma/shells/org.kde.plasma.desktop/contents/layout.js 
    cp -f /usr/share/ezgo/ezgo-kde5/ezgo13_splash.svg /usr/share/plasma/look-and-feel/org.kde.breeze.desktop/contents/splash/images/
    cp -f /usr/share/ezgo/ezgo-kde5/Splash.qml /usr/share/plasma/look-and-feel/org.kde.breeze.desktop/contents/splash/
    cp -f /usr/share/ezgo/ezgo-kde5/kickerdash-metadata.desktop /usr/share/plasma/plasmoids/org.kde.plasma.kickerdash/metadata.desktop
    cp -f /usr/share/ezgo/ezgo-kde5/kicker-main.xml /usr/share/plasma/plasmoids/org.kde.plasma.kicker/contents/config/main.xml
    cp -f /usr/share/ezgo/ezgo-kde5/kickoff-main.xml /usr/share/plasma/plasmoids/org.kde.plasma.kickoff/contents/config/main.xml
    cp -f /usr/share/ezgo/ezgo-artwork/default-dm/1920x1080.png /usr/share/plasma/look-and-feel/org.kde.breeze.desktop/contents/components/artwork/background.png
    sed -ri 's/defaultWallpaperTheme=.+/defaultWallpaperTheme=ezgo/g' /usr/share/plasma/desktoptheme/*/metadata.desktop
    sed -ri 's/defaultWidth=.+/defaultWidth=1920/g' /usr/share/plasma/desktoptheme/*/metadata.desktop
    sed -ri 's/defaultHeight=.+/defaultHeight=1080/g' /usr/share/plasma/desktoptheme/*/metadata.desktop
    ;;
esac
