#!/bin/sh

set -e

#DEBHELPER#

update-alternatives --install /usr/share/plymouth/themes/default.plymouth default.plymouth /usr/share/plymouth/themes/ezgo14/ezgo14.plymouth 200 --slave /usr/share/plymouth/themes/default.grub default.plymouth.grub /usr/share/plymouth/themes/ezgo14/ezgo14.grub 

update-alternatives --set default.plymouth /usr/share/plymouth/themes/ezgo14/ezgo14.plymouth

update-initramfs -u

