ezgo-artwork/sddm/ezgo.png usr/share/sddm/themes/ezgo
ezgo-artwork/sddm/Main.qml usr/share/sddm/themes/ezgo
ezgo-artwork/sddm/metadata.desktop usr/share/sddm/themes/ezgo
ezgo-artwork/sddm/theme.conf usr/share/sddm/themes/ezgo
ezgo-artwork/sddm/dummydata/* usr/share/sddm/themes/ezgo/dummydata
ezgo-artwork/sddm/components/* usr/share/sddm/themes/ezgo/components
ezgo-artwork/sddm/components/artwork/* usr/share/sddm/themes/ezgo/components/artwork
