#! /bin/sh
set -e

case "$1" in
  configure)
    # link desktop files for ezgo
    ln -sf /usr/share/ezgo/desktop-files/7zip.desktop /usr/share/applications/7zip.desktop
    ln -sf /usr/share/ezgo/desktop-files/impressive-editor.desktop /usr/share/applications/impressive-editor.desktop
    ln -sf /usr/share/ezgo/desktop-files/media_install.desktop /usr/share/applications/media_install.desktop
    ln -sf /usr/share/ezgo/desktop-files/media_install_force.desktop /usr/share/applications/media_install_force.desktop
    ln -sf /usr/share/ezgo/desktop-files/my_computer.desktop /usr/share/applications/my_computer.desktop
    ln -sf /usr/share/ezgo/desktop-files/my_ezgo.desktop /usr/share/applications/my_ezgo.desktop
    ln -sf /usr/share/ezgo/desktop-files/about_ezgo.desktop /usr/share/applications/about_ezgo.desktop
    cd /usr/share/ezgo/ezgo-misc
    # 7-zip
    tar xf 7zip.tar.gz
    rm -rf /usr/local/7-Zip
    mv /usr/share/ezgo/ezgo-misc/7-Zip /usr/local/
    rm -f 7zip.tar.gz
    # fix tuxpaint
    sed -i '$ a\sysfonts=yes' /etc/tuxpaint/tuxpaint.conf
    # libreoffice configurations
    tar xf libreoffice.tar.gz
    rm -rf /etc/skel/.config/libreoffice
    mv /usr/share/ezgo/ezgo-misc/libreoffice /etc/skel/.config
    chown -R root.root /etc/skel/.config/libreoffice
    rm -f libreoffice.tar.gz
    ;;
  remove)
	rm -f /usr/share/applications/7zip.desktop
	rm -f /usr/share/applications/impressive-editor.desktop
	rm -f /usr/share/applications/media_install.desktop
	rm -f /usr/share/applications/media_install_force.desktop
	rm -f /usr/share/applications/my_computer.desktop
	rm -f /usr/share/applications/my_ezgo.desktop
	rm -f /usr/share/applications/about_ezgo.desktop
    rm -f /usr/local/7-Zip
    sed -i 's/sysfonts=yes//g' /etc/tuxpaint/tuxpaint.conf
    rm -rf /etc/skel/.config/libreoffice
    ;;
esac
