#! /bin/sh
set -e

case "$1" in
  configure)
    # link desktop files for ezgo
	# put furiusisomount.mo
	if [ ! -e  /usr/share/locale/zh_TW/LC_MESSAGES/furiusisomount.mo.ezgo-bak ]; then
		if [ -e /usr/share/locale/zh_TW/LC_MESSAGES/furiusisomount.mo ]; then
			cp -f  /usr/share/locale/zh_TW/LC_MESSAGES/furiusisomount.mo /usr/share/locale/zh_TW/LC_MESSAGES/furiusisomount.mo.ezgo-bak
		fi
	fi
	rm -f /usr/share/locale/zh_TW/LC_MESSAGES/furiusisomount.mo
	cp -f /usr/share/ezgo/ezgo-misc/translations/furiusisomount.mo /usr/share/locale/zh_TW/LC_MESSAGES/furiusisomount.mo
    # put kdenlive.mo
	if [ ! -e /usr/share/locale/zh_TW/LC_MESSAGES/kdenlive.mo.ezgo-bak ]; then
		if [ -e /usr/share/locale/zh_TW/LC_MESSAGES/kdenlive.mo ]; then
			cp -f  /usr/share/locale/zh_TW/LC_MESSAGES/kdenlive.mo /usr/share/locale/zh_TW/LC_MESSAGES/kdenlive.mo.ezgo-bak
		fi
	fi
	rm -f /usr/share/locale/zh_TW/LC_MESSAGES/kdenlive.mo
	cp -f /usr/share/ezgo/ezgo-misc/translations/kdenlive.mo /usr/share/locale/zh_TW/LC_MESSAGES/kdenlive.mo
    # put pdfshuffler.mo
	if [ ! -e /usr/share/locale/zh_TW/LC_MESSAGES/pdfshuffler.mo.ezgo-bak ]; then
		if [ -e /usr/share/locale/zh_TW/LC_MESSAGES/pdfshuffler.mo ]; then
			cp -f  /usr/share/locale/zh_TW/LC_MESSAGES/pdfshuffler.mo /usr/share/locale/zh_TW/LC_MESSAGES/pdfshuffler.mo.ezgo-bak
		fi
	fi
	rm -f /usr/share/locale/zh_TW/LC_MESSAGES/pdfshuffler.mo
	cp -f /usr/share/ezgo/ezgo-misc/translations/pdfshuffler.mo /usr/share/locale/zh_TW/LC_MESSAGES/pdfshuffler.mo
    # put xournal.mo
	if [ ! -e /usr/share/locale/zh_TW/LC_MESSAGES/xournal.mo.ezgo-bak ]; then
		if [ -e /usr/share/locale/zh_TW/LC_MESSAGES/xournal.mo ]; then
			cp -f  /usr/share/locale/zh_TW/LC_MESSAGES/xournal.mo /usr/share/locale/zh_TW/LC_MESSAGES/xournal.mo.ezgo-bak
		fi
	fi
	rm -f /usr/share/locale/zh_TW/LC_MESSAGES/xournal.mo
	cp -f /usr/share/ezgo/ezgo-misc/translations/xournal.mo /usr/share/locale/zh_TW/LC_MESSAGES/xournal.mo
    # put klavaro.mo
	if [ ! -e /usr/share/locale/zh_TW/LC_MESSAGES/klavaro.mo.ezgo-bak ]; then
		if [ -e /usr/share/locale/zh_TW/LC_MESSAGES/klavaro.mo ]; then
			cp -f  /usr/share/locale/zh_TW/LC_MESSAGES/klavaro.mo /usr/share/locale/zh_TW/LC_MESSAGES/klavaro.mo.ezgo-bak
		fi
	fi
	rm -f /usr/share/locale/zh_TW/LC_MESSAGES/klavaro.mo
	cp -f /usr/share/ezgo/ezgo-misc/translations/klavaro.mo /usr/share/locale/zh_TW/LC_MESSAGES/klavaro.mo
	# put qtqr translations
	if [ -e /usr/share/qt4/translations ]; then
		if [ ! -e /usr/share/qt4/translations/qtqr_zh_TW.qm.ezgo-bak ]; then
			if [ -e /usr/share/qt4/translations/qtqr_zh_TW.qm ]; then
				cp -f /usr/share/qt4/translations/qtqr_zh_TW.qm /usr/share/qt4/translations/qtqr_zh_TW.qm.ezgo-bak
			fi
		fi
		rm -f /usr/share/qt4/translations/qtqr_zh_TW.qm
		cp -f /usr/share/ezgo/ezgo-misc/translations/qtqr_zh_TW.qm /usr/share/qt4/translations/qtqr_zh_TW.qm
	fi
	# fix mime package freedesktop.org.xml for shockwave flash
	if [ -e /usr/share/mime/packages ]; then
		if [ -e /usr/share/mime/packages/freedesktop.org.xml.ezgo-bak ]; then
			mv /usr/share/mime/packages/freedesktop.org.xml.ezgo-bak /usr/share/ezgo/ezgo-misc
		fi
		if [ ! -e /usr/share/ezgo/ezgo-misc/freedesktop.org.xml.ezgo-bak ]; then
			if [ -e /usr/share/mime/packages/freedesktop.org.xml ]; then
				cp -f /usr/share/mime/packages/freedesktop.org.xml  /usr/share/ezgo/ezgo-misc/freedesktop.org.xml.ezgo-bak
			fi
		fi
		rm -f /usr/share/mime/packages/freedesktop.org.xml
		cp -f /usr/share/ezgo/ezgo-misc/freedesktop.org.xml /usr/share/mime/packages/freedesktop.org.xml
		/usr/bin/update-mime-database /usr/share/mime
	fi
    ;;
  remove)
	# remove furiusisomount
	rm -f /usr/share/locale/zh_TW/LC_MESSAGES/furiusisomount.mo
	if [ -e /usr/share/locale/zh_TW/LC_MESSAGES/furiusisomount.mo.ezgo-bak ]; then
		mv /usr/share/locale/zh_TW/LC_MESSAGES/furiusisomount.mo.ezgo-bak /usr/share/locale/zh_TW/LC_MESSAGES/furiusisomount.mo
	fi
	# remove kdenlive
	rm -f /usr/share/locale/zh_TW/LC_MESSAGES/kdenlive.mo
	if [ -e /usr/share/locale/zh_TW/LC_MESSAGES/kdenlive.mo.ezgo-bak ]; then
		mv /usr/share/locale/zh_TW/LC_MESSAGES/kdenlive.mo.ezgo-bak /usr/share/locale/zh_TW/LC_MESSAGES/kdenlive.mo
	fi
	# remove pdfshuffler
	rm -f /usr/share/locale/zh_TW/LC_MESSAGES/pdfshuffler.mo
	if [ -e /usr/share/locale/zh_TW/LC_MESSAGES/pdfshuffler.mo.ezgo-bak ]; then
		mv /usr/share/locale/zh_TW/LC_MESSAGES/pdfshuffler.mo.ezgo-bak /usr/share/locale/zh_TW/LC_MESSAGES/pdfshuffler.mo
	fi
	# remove xournal
	rm -f /usr/share/locale/zh_TW/LC_MESSAGES/xournal.mo
	if [ -e /usr/share/locale/zh_TW/LC_MESSAGES/xournal.mo.ezgo-bak ]; then
		mv /usr/share/locale/zh_TW/LC_MESSAGES/xournal.mo.ezgo-bak /usr/share/locale/zh_TW/LC_MESSAGES/xournal.mo
	fi
	# remove klavaro
	rm -f /usr/share/locale/zh_TW/LC_MESSAGES/klavaro.mo
	if [ -e /usr/share/locale/zh_TW/LC_MESSAGES/klavaro.mo.ezgo-bak ]; then
		mv /usr/share/locale/zh_TW/LC_MESSAGES/klavaro.mo.ezgo-bak /usr/share/locale/zh_TW/LC_MESSAGES/klavaro.mo
	fi
	# remove qtqr
	rm -f /usr/share/qt4/translations/qtqr_zh_TW.qm
	if [ -e /usr/share/qt4/translations/qtqr_zh_TW.qm.ezgo-bak ]; then
		mv /usr/share/qt4/translations/qtqr_zh_TW.qm.ezgo-bak  /usr/share/qt4/translations/qtqr_zh_TW.qm
	fi
	# remove mime package freedesktop.org.xml
	rm -f /usr/share/mime/packages/freedesktop.org.xml
	if [ -e  /usr/share/mime/packages/freedesktop.org.xml.ezgo-bak ]; then
		mv /usr/share/mime/packages/freedesktop.org.xml.ezgo-bak /usr/share/mime/packages/freedesktop.org.xml
    	/usr/bin/update-mime-database /usr/share/mime
	elif [ -e /usr/share/ezgo/ezgo-misc/freedesktop.org.xml.ezgo-bak ]; then
		mv /usr/share/ezgo/ezgo-misc/freedesktop.org.xml.ezgo-bak /usr/share/mime/packages/freedesktop.org.xml
    	/usr/bin/update-mime-database /usr/share/mime
	fi
    ;;
esac
